"""empty message

Revision ID: 6b78a4634f0e
Revises: ab8943d363a8
Create Date: 2020-04-22 10:46:53.053101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b78a4634f0e'
down_revision = 'ab8943d363a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('quiz_id', sa.Integer(), nullable=True),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('ansSubmit', sa.String(length=140), nullable=True),
    sa.Column('mark', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_attempt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_attempt',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('quiz_id', sa.INTEGER(), nullable=True),
    sa.Column('quest_id', sa.INTEGER(), nullable=True),
    sa.Column('ansSubmit', sa.VARCHAR(length=140), nullable=True),
    sa.Column('mark', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quiz_questions.id'], ),
    sa.ForeignKeyConstraint(['quiz_id'], ['quiz.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('quiz_attempts')
    # ### end Alembic commands ###
