"""empty message

Revision ID: de659bad1926
Revises: 44b7e4677e0a
Create Date: 2020-04-17 08:20:09.186088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de659bad1926'
down_revision = '44b7e4677e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['quest_id'], ['quiz_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('quiz_questions', sa.Column('img', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'img')
    op.drop_table('quiz_answers')
    # ### end Alembic commands ###
